export enum ChezaIMAEvent {
  AD_ERROR = 'adError',
  AD_CAN_PLAY = 'adCanPlay',
  AD_BUFFERING = 'adBuffering',
  AD_METADATA = 'adMetadata',
  AD_PROGRESS = 'adProgress',
  AD_CLICK = 'adClick',
  AD_COMPLETE = 'adComplete',
  AD_SKIPPED = 'adSkipped',
  AD_FIRST_QUARTILE = 'adFirstQuartile',
  AD_MIDPOINT = 'adMidpoint',
  AD_THIRD_QUARTILE = 'adThirdQuartile',
  AD_LOADED = 'adLoaded',
  AD_STARTED = 'adStarted',
  AD_PAUSED = 'adPaused',
  AD_RESUMED = 'adResumed',
  AD_VOLUME_CHANGED = 'adVolumeChanged',
  AD_VOLUME_MUTED = 'adVolumeMuted',
}
